# ----------------------------------------------------------------
# Base image with Toolbox
# ----------------------------------------------------------------

FROM debian:13-slim AS base

COPY ./images/install /opt/docker

RUN set -eux \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gzip \
        openssl \
        tar \
        tzdata \
    # Cleanup Docker image \
    && apt autoremove -y \
    && apt clean \
    && /opt/docker/bin/docker-image-cleanup.sh

# ----------------------------------------------------------------
# 3X-UI
# ----------------------------------------------------------------

FROM base

ARG BUILD_DATE
ARG XUI_VERSION

LABEL \
    maintainer="Crasivo Dev <crasivodev@gmail.com>" \
    org.opencontainers.image.authors="MHSanaei (Original), Crasivo Dev (Docker Maintainer)" \
    org.opencontainers.image.title="3X-UI Panel" \
    org.opencontainers.image.description="Multi-protocol control panel for Xray, supporting VLESS, VMess, Trojan, ShadowTLS, and Hysteria2. Built from MHSanaei/3x-ui." \
    org.opencontainers.image.url="https://github.com/MHSanaei/3x-ui" \
    org.opencontainers.image.source="https://github.com/MHSanaei/3x-ui" \
    org.opencontainers.image.documentation="https://github.com/MHSanaei/3x-ui/blob/main/README.md" \
    org.opencontainers.image.version="${XUI_VERSION}" \
    org.opencontainers.image.created="${BUILD_DATE}" \
    org.opencontainers.image.licenses="GPL-3.0" \
    org.opencontainers.image.vendor="MHSanaei & Contributors" \
    org.opencontainers.image.base.name="docker.io/library/alpine:${ALPINE_RELEASE}"

# Legacy environments
ENV XUI_LOG_LEVEL=info \
    XUI_ENABLE_FAIL2BAN=false \
    XUI_DEBUG=false

RUN set -eux \
    # Create group & user \
    && groupadd -g 1000 xray \
    && useradd -m -s /bin/bash -u 1000 -g xray xray \
    # Install XRay & X-UI release \
    && /opt/docker/bin/xui-install.sh "$XUI_VERSION" \
    # Prepare structure \
    && mkdir -p /etc/x-ui /var/log/x-ui /var/log/xray \
    && chown -R xray:xray /etc/x-ui /usr/local/x-ui /var/log/x-ui /var/log/xray \
    && chmod 0700 /etc/x-ui /usr/local/x-ui /var/log/x-ui /var/log/xray \
    # Prepare Docker entrypoint \
    && mkdir -p /docker-entrypoint.d \
    && ln -sf /opt/docker/bin/docker-entrypoint.sh /docker-entrypoint.sh \
    && ln -sf /opt/docker/bin/xui-bootstrap.sh /docker-entrypoint.d/50-xui-bootstrap.sh \
    # Cleanup Docker image \
    && /opt/docker/bin/docker-image-cleanup.sh

WORKDIR /usr/local/x-ui

VOLUME ["/etc/x-ui", "/usr/local/x-ui/bin"]

EXPOSE 2053/tcp 2096/tcp

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/usr/local/x-ui/x-ui", "run"]

HEALTHCHECK --interval=60s --timeout=15s --start-period=30s \
    CMD curl -I 'http://localhost:2053'
